# Generated by Django 4.2.4 on 2023-08-21 13:38

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carsmanager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('driver_license', models.ImageField(blank=True, height_field='heigth_length', null=True, upload_to=booking.models.uploaded_to, width_field='width_length')),
                ('width_length', models.IntegerField(blank=True, default=0, null=True)),
                ('heigth_length', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='PENDING', max_length=200, null=True)),
                ('booked_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carsmanager.car')),
                ('booked_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.driver')),
            ],
        ),
    ]
