# Generated by Django 4.2.4 on 2023-09-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '__first__'),
        ('carsmanager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('RETURNED', 'RETURNED')], default='PENDING', max_length=200, null=True)),
                ('booked_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carsmanager.car')),
                ('booked_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
