# Generated by Django 4.2.5 on 2023-10-03 10:50

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='heigth_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signature',
            field=models.ImageField(blank=True, height_field='heigth_length', null=True, upload_to=booking.models.uploaded_to, width_field='width_length'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='width_length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
