# Generated by Django 4.2.5 on 2023-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_agreement_heigth_length_agreement_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
