# Generated by Django 4.2.5 on 2023-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_agreement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
