# Generated by Django 4.2.5 on 2023-09-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_categories',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='car_engines',
            name='engine',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='car_transmission',
            name='transmission',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
