# Generated by Django 4.2.5 on 2023-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_alter_car_categories_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
