# Generated by Django 4.2.5 on 2023-09-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup.car_brand'),
        ),
    ]
