# Generated by Django 4.2.4 on 2023-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='price_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
