# Generated by Django 4.2.4 on 2023-09-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
