# Generated by Django 4.2.5 on 2023-09-14 09:49

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('driver_license', models.ImageField(blank=True, height_field='heigth_length', null=True, upload_to=customer.models.uploaded_to, width_field='width_length')),
                ('width_length', models.IntegerField(blank=True, default=0, null=True)),
                ('heigth_length', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
