# Generated by Django 4.2.4 on 2023-08-21 13:38

import carsmanager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_year', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('plate_number', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SMALL', 'SMALL'), ('MIDSIZE', 'MIDSIZE'), ('PREMIUM', 'PREMIUM'), ('SUV', 'SUV'), ('VAN', 'VAN')], max_length=200)),
                ('seat_number', models.IntegerField()),
                ('engine_type', models.CharField(choices=[('ELECTRIC', 'ELECTRIC'), ('HYBRID', 'HYBRID'), ('PETROL', 'PETROL'), ('DIESEL', 'DIESEL')], max_length=200)),
                ('transmission_type', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('MANUAL', 'MANUAL')], max_length=200)),
                ('images', models.ImageField(blank=True, null=True, upload_to=carsmanager.models.uploaded_to)),
                ('width_length', models.IntegerField(blank=True, default=0, null=True)),
                ('heigth_length', models.IntegerField(blank=True, default=0, null=True)),
                ('price_per_day', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
