# Generated by Django 4.2.3 on 2023-08-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
