# Generated by Django 4.2.5 on 2023-09-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_car_brand'),
        ('carsmanager', '0002_alter_car_category_alter_car_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookup.car_brand'),
        ),
    ]
